#!/bin/bash

composer require gingerpay/payment

mkdir GingerPay
cp -r vendor/gingerpay/payment GingerPay/Payment
cd GingerPay/Payment/Library/
composer install

cd ../../../

rm -r vendor/
rm composer.lock 
rm composer.json 

